export type Story = { slug: string; title: string; dek: string; section: string; date: string; read: string; image: string; author: string; body: string[] };

export const stories: Story[] = [
  { slug: "campus-after-the-monsoon", title: "After the monsoon, a campus learns to find its way", dek: "On the paths, puddles and small routines that shape life at Shiv Nadar University.", section: "SNU", date: "September 18, 2026", read: "6 min read", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85", author: "Dhrithi Shashibushan", body: ["At first light, the campus is still damp. Rain beads on the gulmohar leaves and gathers in the shallow dips along the road between the hostels and the academic blocks. The day begins in small negotiations with the weather: a longer route, a borrowed umbrella, a pause beneath the awning.", "These ordinary passages rarely make it into the official account of a university. Yet they are where a campus becomes legible to the people who live in it. Students learn which path dries first, where the morning light falls, and how much time to leave when the sky turns dark.", "University Avenue is an independent journal of those details and the larger questions they lead us to ask. This is a dispatch from a place still becoming itself."] },
  { slug: "the-library-is-a-living-room", title: "The library is becoming the campus living room", dek: "A closer look at the shared spaces students make their own between classes.", section: "People", date: "September 12, 2026", read: "5 min read", image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1200&q=85", author: "Dhrithi Shashibushan", body: ["By late afternoon, the quietest floor is not always the quietest place. Chairs turn toward one another; a table becomes a meeting room, then a dining table, then a place to sit without needing a reason.", "The university library was designed for books and study. Students have added something less easy to draw on a plan: a sense of belonging that comes from being around other people, even when nobody is speaking."] },
  { slug: "who-gets-to-feel-at-home", title: "Who gets to feel at home on a new campus?", dek: "Belonging is built in the everyday gestures that make a place feel shared.", section: "Ideas", date: "September 04, 2026", read: "8 min read", image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85", author: "Dhrithi Shashibushan", body: ["A campus can be open on a map and still take time to feel welcoming. The feeling arrives through people: the classmate who saves a seat, the senior who explains where to go, the familiar face at the café.", "Thinking about belonging means paying attention to who finds those doors easily and who has to search for them. It asks us to treat welcome as a practice, not a slogan."] },
  { slug: "a-stage-under-the-stars", title: "A stage under the stars, made by students", dek: "The people behind the late-night rehearsals and the campus performances they bring to life.", section: "Events", date: "August 27, 2026", read: "4 min read", image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=85", author: "Dhrithi Shashibushan", body: ["The first audience arrives while the light is still blue. Behind the stage, someone checks a cable, another smooths a costume, and the cast runs a final line under their breath.", "Campus performances are temporary by nature, but the work that brings them together leaves a longer trace: new collaborations, new confidence and a reason to gather."] },
  { slug: "small-grants-big-questions", title: "Small grants, big questions: funding student research", dek: "What early-career researchers need to turn a good question into a project.", section: "Opportunities", date: "August 19, 2026", read: "7 min read", image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=85", author: "Dhrithi Shashibushan", body: ["For students with a research question, the first obstacle is often not an answer but a budget. A modest grant can pay for materials, local travel or the time needed to learn a new method.", "Faculty mentors say the strongest proposals begin small and clear. The point is not to solve everything at once; it is to make the next step possible."] },
];

export const sections = ["SNU", "People", "Ideas", "Events", "Opportunities"];
export const events = [
  { day: "26", month: "SEP", title: "Open mic on the lawn", detail: "Student Centre · 6:30 pm", type: "Community" },
  { day: "29", month: "SEP", title: "The future of public health", detail: "Auditorium 2 · 5:00 pm", type: "Talk" },
  { day: "03", month: "OCT", title: "Autumn makers market", detail: "Central courtyard · 11:00 am", type: "Campus life" },
];
export const opportunities = [
  { label: "RESEARCH · APPLY BY 04 OCT", title: "Undergraduate Research Fellowship", detail: "A semester-long opportunity to work with a faculty mentor on an independent research question.", action: "Explore the fellowship" },
  { label: "WRITING · APPLY BY 10 OCT", title: "Campus Voices: student writing call", detail: "Pitch a reported story, photo essay or personal reflection about life at SNU.", action: "View the open call" },
  { label: "INTERNSHIP · APPLY BY 15 OCT", title: "Centre for Public Policy internship", detail: "Join a student team supporting research, communications and public events.", action: "See role details" },
];
