import Link from "next/link";
import { getCurrentProfile } from "../lib/auth";
import { signOut } from "../lib/actions/auth";
import { PrimaryNavigation } from "./primary-navigation";
import type { Story } from "../lib/types";

export async function Header() {
  const profile = await getCurrentProfile();

  return <><div className="topline"><span>An independent production</span><span>ISSUE 01 &nbsp; / &nbsp; AUTUMN 2026</span></div><header className="header wrap"><Link className="wordmark" href="/">University<span> Avenue</span><i>®</i></Link><PrimaryNavigation profile={profile ? { role: profile.role, status: profile.status } : null}/><Link className="pitch" href="/about#contact">Pitch a story <span>↗</span></Link><div className="header-auth">{profile?.status === "active" ? <><span className="header-account">{profile.display_name}<small>{profile.role === "admin" ? "Admin" : "Contributor"}</small></span><form action={signOut}><button className="auth-nav-button" type="submit">Log out</button></form></> : <><Link href="/login">Sign in</Link><Link className="contributor-link" href="/signup">Become a contributor</Link></>}</div></header></>;
}
export function Footer() { return <footer className="footer"><div className="wrap footer-grid"><div><Link className="wordmark" href="/">University<span> Avenue</span></Link><p>An independent journal of university life.<br/>Made at Shiv Nadar University.</p></div><div><small>EXPLORE</small><Link href="/snu">SNU</Link><Link href="/people">People</Link><Link href="/ideas">Editorial</Link></div><div><small>MORE</small><Link href="/events">Events</Link><Link href="/opportunities">Opportunities</Link><Link href="/about">About us</Link></div><div><small>GET IN TOUCH</small><a href="mailto:dhrithishashibushan@gmail.com">dhrithishashibushan@gmail.com</a><Link href="/authors/dhrithi-shashibushan">Our contributors</Link></div></div><div className="wrap footnote"><span>© 2026 University Avenue</span><span aria-hidden="true"></span></div></footer> }
export function Shell({ children }: { children: React.ReactNode }) { return <><Header/>{children}<Footer/></> }
export function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="eyebrow"><span>{children}</span><i/></div> }
export function StoryCard({ story, feature = false }: { story: Story; feature?: boolean }) { return <article className={feature ? "story-card feature-card" : "story-card"}><div className="story-visual"><Link className="story-image" href={`/stories/${story.slug}`} style={{ backgroundImage: `url("${story.image}")` }} aria-label={`Read ${story.title}: ${story.imageAlt || story.title}`} />{story.imageAlt.trim() && <p className="story-image-caption">{story.imageAlt}</p>}</div><div className="story-copy"><div className="story-meta"><span>{story.section}</span><b>·</b><time>{story.date}</time></div><h3><Link href={`/stories/${story.slug}`}>{story.title}</Link></h3><p>{story.dek}</p><div className="byline">By <Link href={`/authors/${story.authorSlug}`}>{story.author}</Link><span>{story.read}</span></div></div></article> }
export function SectionHeading({ title, note, href }: { title: string; note?: string; href?: string }) { return <div className="section-heading"><div><Eyebrow>{note || "FROM THE AVENUE"}</Eyebrow><h2>{title}</h2></div>{href && <Link className="text-link" href={href}>View all stories <span>↗</span></Link>}</div> }
