import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { stories } from "../../lib/content";
import { Eyebrow, Shell, StoryCard } from "../../components/site";

export function generateStaticParams(){return stories.map(story=>({slug:story.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const story=stories.find(s=>s.slug===slug);if(!story)return {};return {title:story.title,description:story.dek,openGraph:{title:story.title,description:story.dek,images:[story.image]}}}
export default async function StoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const story=stories.find(s=>s.slug===slug);if(!story)notFound();const more=stories.filter(s=>s.slug!==slug).slice(0,2);return <Shell><main className="wrap"><div className="article-layout"><article><header className="article-head"><Eyebrow>{story.section} · {story.date}</Eyebrow><h1>{story.title}</h1><p className="dek">{story.dek}</p><div className="article-byline">By <Link href="/authors/dhrithi-shashibushan">{story.author}</Link><span>{story.read}</span></div></header><div className="article-cover" role="img" aria-label="Campus scene" style={{backgroundImage:`url("${story.image}")`}}/><div className="article-body">{story.body.map((p,i)=><p key={i}>{p}</p>)}</div></article><aside className="article-aside"><small>THE AVENUE</small><p>University Avenue</p><Link href="/snu" className="text-link">More from SNU ↗</Link></aside></div><section className="section-block"><div className="section-heading"><div><Eyebrow>KEEP READING</Eyebrow><h2>More from the avenue</h2></div></div><div className="listing-grid">{more.map(s=><StoryCard key={s.slug} story={s}/>)}</div></section></main></Shell>}
