import { notFound } from "next/navigation";
import Link from "next/link";
import { stories, sections, events, opportunities } from "../lib/content";
import { Eyebrow, SectionHeading, Shell, StoryCard } from "../components/site";

const intros: Record<string, { title: string; deck: string }> = { snu: { title: "Spotlight on SNU", deck: "Campus chatter, major (and small) events, someone spotting a cloud shaped like a lion– it’s all here!" }, people: { title: "People", deck: "Meet students, faculty, and even alumni. They’re cool people!" }, ideas: { title: "Editorial – Contributor perspectives", deck: "Join us on a journey through different perspectives that shed light on how we learn, live, and belong." }, events: { title: "The Campus Calender", deck: "Bored, and looking for something to do? Take a moment to peruse through campus activities– you’re sure to find something you love." }, opportunities: { title: "Room to begin.", deck: "Open calls, research support, internships and ways to take your next step." } };
export function generateStaticParams() { return [...sections.map(s => ({section:s.toLowerCase()})), {section:"about"}]; }
export default async function SectionPage({ params }: {params: Promise<{section:string}>}) { const {section} = await params; const key=section.toLowerCase(); if(key === "about") return <About/>; const intro=intros[key]; if(!intro) notFound(); const list=stories.filter(s=> key==="snu" || s.section.toLowerCase()===key); return <Shell><main className="wrap"><header className="page-intro"><Eyebrow>UNIVERSITY AVENUE / {key.toUpperCase()}</Eyebrow><h1 className={key === "ideas" ? "editorial-page-title" : undefined}>{intro.title}</h1><p>{intro.deck}</p></header>{key === "events" ? <div className="list-items">{events.map(e=><article key={e.title}><Eyebrow>{e.type} · {e.month} {e.day}</Eyebrow><h2>{e.title}</h2><p>{e.detail}</p></article>)}</div> : key === "opportunities" ? <><section className="section-block opportunity-stories"><SectionHeading title="Opportunity stories" note="REPORTING & EXPLAINERS"/><div className="listing-grid">{stories.filter(s=>s.section.toLowerCase()==="opportunities").map(s=><StoryCard key={s.slug} story={s}/>)}</div></section><section className="section-block opportunity-deadlines"><SectionHeading title="Opportunities & deadlines" note="SAMPLE DATA · NOT VERIFIED CURRENT OPPORTUNITIES"/><div className="events-strip">{opportunities.map(o=><article className="event-item opportunity-item" key={o.title}><div className="event-date"><b>{o.deadlineDay}</b><span>{o.deadlineMonth}</span></div><div className="opportunity-details"><small>SAMPLE LISTING · {o.category}</small><h3>{o.title}</h3><p>{o.detail}</p><p>{o.organization} · Deadline: {o.deadline}</p><p>Eligibility: {o.eligibility} · {o.location}</p><a href={o.actionHref}>{o.actionLabel} ↗</a></div><span className="arrow" aria-hidden="true">↗</span></article>)}</div></section></> : <><SectionHeading title={key === "snu" ? "Recent dispatches" : `From the ${key === "ideas" ? "editorial" : key} desk`} note="STORIES & PERSPECTIVES"/><div className="listing-grid">{list.length ? list.map(s=><StoryCard key={s.slug} story={s}/>) : <p className="empty-note">Nothing here yet.</p>}</div></>}</main></Shell> }

function About(){return <Shell><main className="wrap"><header className="page-intro"><Eyebrow>ABOUT THE AVENUE</Eyebrow><h1>Made with curiosity, rooted at SNU.</h1><p>An independent journal about the people, ideas and everyday life of a university community.</p></header><section className="about-copy"><p>We begin at Shiv Nadar University, where a changing campus offers an endless supply of stories worth noticing.</p><p>We strive to offer you a collection of stories covering anything interesting, important, and relevant happening on campus.</p><p>This is an independent student-led publication, with the goal of showcasing how life truly unfolds at university, beyond the glamourous curation of a pamphlet. It is a platform meant to cater to professors, parents, alumni, recruiters, and ofcourse– the students, both current and aspiring.</p><p>Our first edition is a starting point. Over time, University Avenue hopes to connect campus communities across India and the world through a shared love for writing, new ideas, and honest journalism.</p><h2>Come tell us what you see.</h2><p>Have a story or question for us? We’d love to hear from you. Please reach out at <a href="mailto:hello@universityavenue.in">[email]</a>. Meet our contributors <Link href="/authors/dhrithi-shashibushan">[Go to contributor page.]</Link></p></section></main></Shell>}
