import { notFound } from "next/navigation";
import Link from "next/link";
import { stories, sections, events, opportunities } from "../lib/content";
import { Eyebrow, SectionHeading, Shell, StoryCard } from "../components/site";

const intros: Record<string, { title: string; deck: string }> = { snu: { title: "SNU, in focus.", deck: "Reported stories and considered perspectives from Shiv Nadar University — the people, places and questions shaping campus life." }, people: { title: "People make a place.", deck: "Meet the students, faculty, makers and neighbours shaping life at Shiv Nadar University." }, ideas: { title: "Ideas for the in-between.", deck: "Essays, questions and perspectives from a community thinking about what comes next." }, events: { title: "The campus calendar.", deck: "Gatherings, talks and moments worth making time for across the SNU community." }, opportunities: { title: "Room to begin.", deck: "Open calls, research support, internships and ways to take your next step." } };
export function generateStaticParams() { return [...sections.map(s => ({section:s.toLowerCase()})), {section:"about"}]; }
export default async function SectionPage({ params }: {params: Promise<{section:string}>}) { const {section} = await params; const key=section.toLowerCase(); if(key === "about") return <About/>; const intro=intros[key]; if(!intro) notFound(); const list=stories.filter(s=> key==="snu" || s.section.toLowerCase()===key); return <Shell><main className="wrap"><header className="page-intro"><Eyebrow>UNIVERSITY AVENUE / {key.toUpperCase()}</Eyebrow><h1>{intro.title}</h1><p>{intro.deck}</p></header>{key === "events" ? <div className="list-items">{events.map(e=><article key={e.title}><Eyebrow>{e.type} · {e.month} {e.day}</Eyebrow><h2>{e.title}</h2><p>{e.detail}. A chance to listen, meet and spend an evening with people from across campus.</p></article>)}</div> : key === "opportunities" ? <div className="list-items">{opportunities.map(o=><article key={o.title}><Eyebrow>{o.label}</Eyebrow><h2>{o.title}</h2><p>{o.detail}</p><a className="text-link" href="mailto:hello@universityavenue.in?subject=Opportunity%20details">{o.action} ↗</a></article>)}</div> : <><SectionHeading title={key === "snu" ? "Recent dispatches" : `From the ${key} desk`} note="STORIES & PERSPECTIVES"/><div className="listing-grid">{list.length ? list.map(s=><StoryCard key={s.slug} story={s}/>) : <p className="empty-note">A new story is on its way. Check back soon.</p>}</div></>}</main></Shell> }

function About(){return <Shell><main className="wrap"><header className="page-intro"><Eyebrow>ABOUT THE AVENUE</Eyebrow><h1>A university is<br/><em>more than its walls.</em></h1><p>University Avenue is an independent journal about the people, ideas and everyday life of a university community.</p></header><section className="about-copy"><h2>Made with curiosity, rooted at SNU.</h2><p>We begin at Shiv Nadar University, where a changing campus offers an endless supply of stories worth noticing. We believe independent university journalism makes room for voices, questions and experiences that don’t always fit inside an announcement.</p><p>Our first edition is a starting point. Over time, University Avenue hopes to connect campus communities across India through careful reporting, generous conversation and a shared love of ideas.</p><h2>Come tell us what you see.</h2><p>Have a story, a question, or a perspective we should hear? Write to <a href="mailto:hello@universityavenue.in">hello@universityavenue.in</a>.</p><p><Link href="/authors/dhrithi-shashibushan">Meet Dhrithi Shashibushan, contributing writer →</Link></p></section></main></Shell>}
