import Link from "next/link";
import { stories, events, opportunities } from "./lib/content";
import { Eyebrow, SectionHeading, Shell, StoryCard } from "./components/site";

export default function Home() { const [lead, ...rest] = stories; return <Shell><main><section className="hero wrap"><div className="hero-copy"><Eyebrow>AN INDEPENDENT CAMPUS JOURNAL</Eyebrow><p className="hero-kicker">A place to begin.<br/>A world to pay attention to.</p><h1>University life,<br/><em>closely observed.</em></h1><p className="hero-dek">Stories, people and ideas from Shiv Nadar University — and the communities that make a campus more than a place to study.</p><Link className="button" href="/snu">Explore the journal <span>↗</span></Link></div><div className="hero-photo" style={{backgroundImage:`url("${lead.image}")`}}><span className="photo-caption">A campus after the rain · SNU</span></div></section>
<div className="wrap ticker"><span>NOW ON THE AVENUE</span><p>Reporting from a university in motion</p><Link href="/about">Who we are ↗</Link></div>
<section className="wrap section-block"><SectionHeading title="On the avenue" note="THE LATEST" href="/snu"/><div className="story-grid"><StoryCard story={lead} feature/><div className="secondary-stories">{rest.slice(0,3).map(s=><StoryCard key={s.slug} story={s}/>)}</div></div></section>
<section className="ideas-band"><div className="wrap ideas-layout"><div><Eyebrow>THE CAMPUS, IN QUESTION</Eyebrow><h2>Ideas worth<br/><em>walking with.</em></h2><p>Essays and perspectives on the forces shaping how we learn, live and belong.</p><Link className="button button-light" href="/ideas">Read the ideas desk ↗</Link></div><StoryCard story={stories[2]}/></div></section>
<section className="wrap section-block"><SectionHeading title="Coming together" note="AROUND CAMPUS" href="/events"/><div className="events-strip">{events.map(e=><article className="event-item" key={e.title}><div className="event-date"><b>{e.day}</b><span>{e.month}</span></div><div><small>{e.type}</small><h3>{e.title}</h3><p>{e.detail}</p></div><span className="arrow">↗</span></article>)}</div></section>
<section className="wrap section-block opportunities-block"><div><Eyebrow>ROOM TO GROW</Eyebrow><h2>Make your next<br/><em>move here.</em></h2><p>Open calls, research grants and opportunities from across the university.</p><Link className="text-link" href="/opportunities">Browse opportunities ↗</Link></div><div className="opportunity-preview">{opportunities.slice(0,2).map(o=><article key={o.title}><small>{o.label}</small><h3>{o.title}</h3><p>{o.detail}</p><Link href="/opportunities">Learn more ↗</Link></article>)}</div></section></main></Shell> }
