import Link from "next/link";
import { stories, events, opportunities } from "./lib/content";
import { Eyebrow, SectionHeading, Shell, StoryCard } from "./components/site";

export default function Home() { const [lead, ...rest] = stories; return <Shell><main><section className="hero wrap"><div className="hero-copy"><Eyebrow>AN INDEPENDENT CAMPUS JOURNAL</Eyebrow><p className="hero-kicker">You’d never believe what happened today… if we hadn’t recorded it!</p><h1>University life, <em>honestly narrated.</em></h1><p className="hero-dek">People, communities, academia, ideas – and everything else that makes our campus… well, SNU!</p><Link className="button" href="/snu">Explore the journal <span>↗</span></Link></div><div className="hero-photo" style={{backgroundImage:`url("${lead.image}")`}}><span className="photo-caption">A campus after the rain · SNU</span></div></section>
<div className="wrap ticker"><span>NOW ON THE AVENUE</span><p>Stories from a university in motion</p><Link href="/about">Who we are ↗</Link></div>
<section className="wrap section-block"><SectionHeading title="On the avenue" note="THE LATEST" href="/snu"/><div className="story-grid"><StoryCard story={lead} feature/><div className="secondary-stories">{rest.slice(0,3).map(s=><StoryCard key={s.slug} story={s}/>)}</div></div></section>
<section className="ideas-band"><div className="wrap ideas-layout"><div><Eyebrow>THE CAMPUS, IN QUESTION</Eyebrow><h2>Editorials</h2><p>Join us on a journey through different perspectives that shed light on how we learn, live, and belong.</p><Link className="button button-light" href="/ideas">Read the editorial desk ↗</Link></div><StoryCard story={stories[2]}/></div></section>
<section className="wrap section-block"><SectionHeading title="Coming together" note="AROUND CAMPUS" href="/events"/><div className="events-strip">{events.map(e=><article className="event-item" key={e.title}><div className="event-date"><b>{e.day}</b><span>{e.month}</span></div><div><small>{e.type}</small><h3>{e.title}</h3><p>{e.detail}</p></div><span className="arrow">↗</span></article>)}</div></section>
<section className="wrap section-block opportunities-block"><div><Eyebrow>ROOM TO GROW</Eyebrow><h2>Opportunities</h2><p>Open OCJ positions, research support, internship opportunities– one stop shop to plan your next move.</p><Link className="text-link" href="/opportunities">Browse opportunities ↗</Link></div><div className="opportunity-preview">{opportunities.slice(0,2).map(o=><article key={o.title}><small>{o.label}</small><h3>{o.title}</h3><p>{o.detail}</p><Link href="/opportunities">Learn more ↗</Link></article>)}</div></section></main></Shell> }
